<template>
  <div class="the-footer">
    <p>关于 | 帮助 | 条款 | 反馈</p>
    <p>Copyright 1998 - 2021 Sou. All Rights Reserved</p>
  </div>
</template>

<script>
export default {
  name: 'TheFooter',
  data () {
    return {}
  },
  // 生命周期 - 创建完成（访问当前this实例）
  created () {},
  // 生命周期 - 挂载完成（访问DOM元素）
  mounted () {}
}
</script>
<style lang='scss' scoped>
/* @import url(); 引入css类 */
@import '../assets/css/the-footer.scss'
</style>
